### ISSUE TITLE
When having the option "Color Reacts to environment and inputs" disabled the mod doesn't work correctly.

### ISSUE THREAD

**Issue by LeCloutPanda** [Ap6661/LaserRecolorJank#4]
When turning that option off and respawning it just stops the process and doesn't set the colours at all and just leaves them blue.

It seems that this code just fails if the value is off
```cs
var ReactiveToggle = Assets.AttachComponent<ValueField<bool>>();
ReactiveToggle.Value.Value = config.GetValue(REACTIVE);
ReactiveEnableds.Add(ReactiveToggle.Value); 
ReactiveToggle.Disposing += (field) => {ReactiveEnableds.Remove(ReactiveToggle.Value); }; 
```

To remedy a simple if check to see if the value is on should suffice.

I've provided screenshots of when the value is off
![image](https://github.com/Ap6661/LaserRecolorJank/assets/53411604/d0f357b3-6bfe-498c-8002-78a610a41e5b)
and when it's on
![image](https://github.com/Ap6661/LaserRecolorJank/assets/53411604/05fad16c-ea2a-401d-8afa-4b6f602fe3b3)

**Comment by Ap6661** [comment]
Turns out I was setting the onFalse for if the reactivity is on to be the default and not the desired color. ( Line 319 )
